# Server configurations
server.port=8080
server.servlet.context-path=

# Database configurations (H2 File Database for dev persistence)
spring.datasource.url=jdbc:h2:file:./data/novabankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# active AI Provider selection (google | ollama)
novabank.ai.provider=${NOVABANK_AI_PROVIDER:ollama}

# Spring AI Google GenAI Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY:}
spring.ai.google.genai.chat.options.model=gemini-2.0-flash
spring.ai.google.genai.chat.options.temperature=0.2

# Spring AI Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
# mistral can be in place of llama3
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.options.temperature=0.2

# JWT Security parameters
novabank.app.jwtSecret=9a67471ec633f4a3eec5378c290feec1ca377e2faa643a841db290feec1ca377e2faa643a841db290feec1ca377
novabank.app.jwtExpirationMs=86400000

# Logging level
logging.level.com.novabank=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
